# Generated by Django 3.2.6 on 2022-08-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('marks', models.FloatField()),
                ('roll_num', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('resume', models.FileField(upload_to='resume/')),
            ],
        ),
    ]
